import 'dart:io';
import 'package:bloc/bloc.dart';
import 'package:dio/dio.dart';
import 'package:dres/features/sell/data/repositories/sell_repository.dart';
import 'ai_listing_event.dart';
import 'ai_listing_state.dart';

class AIListingBloc extends Bloc<AIListingEvent, AIListingState> {
  final SellRepository _repository;

  AIListingBloc({required SellRepository repository})
      : _repository = repository,
        super(const AIListingState()) {
    on<AIListingImagesAdded>(_onImagesAdded);
    on<AIListingImageRemoved>(_onImageRemoved);
    on<AIListingDescriptionUpdated>(_onDescriptionUpdated);
    on<AIListingSizesUpdated>(_onSizesUpdated);
    on<AIListingPriceUpdated>(_onPriceUpdated);
    on<AIListingDepartmentUpdated>(_onDepartmentUpdated);
    on<AIListingCollectionUpdated>(_onCollectionUpdated);
    on<AIListingCategoryUpdated>(_onCategoryUpdated);
    on<AIListingStockUpdated>(_onStockUpdated);
    on<AIListingBrandUpdated>(_onBrandUpdated);
    on<AIListingAuthenticityUpdated>(_onAuthenticityUpdated);
    on<AIListingSubmitted>(_onSubmitted);
    on<AIListingReset>(_onReset);
  }

  void _onImagesAdded(
    AIListingImagesAdded event,
    Emitter<AIListingState> emit,
  ) {
    final updatedImages = List<File>.from(state.images)..addAll(event.images);
    emit(state.copyWith(
      images: updatedImages,
      status: AIListingStatus.editing,
    ));
  }

  void _onImageRemoved(
    AIListingImageRemoved event,
    Emitter<AIListingState> emit,
  ) {
    final updatedImages = List<File>.from(state.images)..removeAt(event.index);
    emit(state.copyWith(
      images: updatedImages,
      status: AIListingStatus.editing,
    ));
  }

  void _onDescriptionUpdated(
    AIListingDescriptionUpdated event,
    Emitter<AIListingState> emit,
  ) {
    emit(state.copyWith(
      description: event.description,
      status: AIListingStatus.editing,
    ));
  }

  void _onSizesUpdated(
    AIListingSizesUpdated event,
    Emitter<AIListingState> emit,
  ) {
    emit(state.copyWith(
      sizes: event.sizes,
      status: AIListingStatus.editing,
    ));
  }

  void _onPriceUpdated(
    AIListingPriceUpdated event,
    Emitter<AIListingState> emit,
  ) {
    emit(state.copyWith(
      prices: event.prices,
      status: AIListingStatus.editing,
    ));
  }

  void _onDepartmentUpdated(
    AIListingDepartmentUpdated event,
    Emitter<AIListingState> emit,
  ) {
    emit(state.copyWith(
      department: event.department,
      status: AIListingStatus.editing,
    ));
  }

  void _onCollectionUpdated(
    AIListingCollectionUpdated event,
    Emitter<AIListingState> emit,
  ) {
    emit(state.copyWith(
      collection: event.collection,
      status: AIListingStatus.editing,
    ));
  }

  void _onCategoryUpdated(
    AIListingCategoryUpdated event,
    Emitter<AIListingState> emit,
  ) {
    emit(state.copyWith(
      category: event.category,
      status: AIListingStatus.editing,
    ));
  }

  void _onStockUpdated(
    AIListingStockUpdated event,
    Emitter<AIListingState> emit,
  ) {
    emit(state.copyWith(
      stocks: event.stocks,
      status: AIListingStatus.editing,
    ));
  }

  void _onBrandUpdated(
    AIListingBrandUpdated event,
    Emitter<AIListingState> emit,
  ) {
    emit(state.copyWith(
      brand: event.brand,
      status: AIListingStatus.editing,
    ));
  }

  void _onAuthenticityUpdated(
    AIListingAuthenticityUpdated event,
    Emitter<AIListingState> emit,
  ) {
    emit(state.copyWith(
      authenticity: event.authenticity,
      status: AIListingStatus.editing,
    ));
  }

  Future<void> _onSubmitted(
    AIListingSubmitted event,
    Emitter<AIListingState> emit,
  ) async {
    if (!state.isValid) {
      emit(state.copyWith(
        status: AIListingStatus.failure,
        errorMessage: 'Please fill in all required fields',
      ));
      return;
    }

    try {
      // Step 1: Upload images
      emit(state.copyWith(
        status: AIListingStatus.uploadingImages,
        uploadProgress: 0.0,
      ));

      final uploadedImageIds = <String>[];
      for (var i = 0; i < state.images.length; i++) {
        final result = await _repository.uploadImage(state.images[i]);
        uploadedImageIds.add(result['id']!);

        // Update progress
        final progress = (i + 1) / state.images.length;
        emit(state.copyWith(uploadProgress: progress));
      }

      emit(state.copyWith(
        uploadedImageIds: uploadedImageIds,
        status: AIListingStatus.submitting,
      ));

      // Step 2: Submit to AI endpoint (description auto-generated by backend)
      final response = await _repository.createProductWithAI(
        imageIds: uploadedImageIds,
        sizes: state.sizes,
        prices: state.prices,
        department: state.department!,
        collection: state.collection!,
        category: state.category!,
        stocks: state.stocks,
        brand: state.brand,
        authenticity: state.authenticity,
      );

      if (response.success) {
        emit(state.copyWith(
          status: AIListingStatus.success,
          createdStyleId: response.styleId,
        ));
      } else {
        emit(state.copyWith(
          status: AIListingStatus.failure,
          errorMessage: 'Failed to create listing',
        ));
      }
    } catch (e) {
      // Extract clean error message from Payload's standard error format
      String errorMessage = 'Failed to create listing';

      print('🔴 AIListingBloc: Caught error: $e');

      if (e is DioException && e.response?.data != null) {
        print('🔴 Response status: ${e.response?.statusCode}');
        print('🔴 Response data: ${e.response?.data}');

        try {
          final data = e.response!.data;
          // Try to parse Payload's standard error format: { errors: [{ message: "..." }] }
          if (data is Map && data['errors'] != null && data['errors'] is List) {
            final errors = data['errors'] as List;
            print('🔴 Found errors array: $errors');
            if (errors.isNotEmpty && errors[0] is Map) {
              errorMessage = errors[0]['message'] ?? errorMessage;
              print('🔴 Extracted error message: $errorMessage');
            }
          } else {
            print('🔴 No errors array found in response');
          }
        } catch (parseError) {
          print('🔴 Error parsing response: $parseError');
          // If parsing fails, use default message
          errorMessage = 'Failed to create listing';
        }
      } else {
        print('🔴 Not a DioException or no response data');
      }

      print('🔴 Final error message: $errorMessage');

      emit(state.copyWith(
        status: AIListingStatus.failure,
        errorMessage: errorMessage,
      ));
    }
  }

  void _onReset(
    AIListingReset event,
    Emitter<AIListingState> emit,
  ) {
    emit(const AIListingState());
  }
}
