import type { Payload } from 'payload'

const fashionBrands = [
  // Luxury Fashion Houses
  { name: 'Nike', description: 'American athletic footwear and apparel corporation' },
  { name: 'Adidas', description: 'German multinational sportswear manufacturer' },
  { name: 'Gucci', description: 'Italian luxury fashion house' },
  { name: 'Louis Vuitton', description: 'French luxury fashion house and company' },
  { name: 'Chanel', description: 'French luxury fashion house' },
  { name: 'Prada', description: 'Italian luxury fashion house' },
  { name: 'Hermès', description: 'French luxury goods manufacturer' },
  { name: 'Burberry', description: 'British luxury fashion house' },
  { name: 'Versace', description: 'Italian luxury fashion company' },
  { name: 'Dior', description: 'French luxury fashion house' },
  { name: 'Balenciaga', description: 'Spanish luxury fashion house' },
  { name: 'Fendi', description: 'Italian luxury fashion house' },
  { name: 'Givenchy', description: 'French luxury fashion and perfume house' },
  { name: 'Saint Laurent', description: 'French luxury fashion house' },
  { name: 'Valentino', description: 'Italian luxury fashion house' },
  { name: 'Bottega Veneta', description: 'Italian luxury fashion house' },
  { name: 'Loewe', description: 'Spanish luxury fashion house' },
  { name: 'Celine', description: 'French luxury fashion house' },
  { name: 'Alexander McQueen', description: 'British luxury fashion house' },
  { name: 'Off-White', description: 'Italian luxury fashion label' },
  { name: 'Max Mara', description: 'Italian fashion house' },
  { name: 'Miu Miu', description: 'Italian fashion house owned by Prada' },
  { name: 'Tom Ford', description: 'American luxury fashion brand' },
  { name: 'Gianvito Rossi', description: 'Italian luxury footwear brand' },
  { name: 'Ganni', description: 'Danish fashion brand' },
  { name: 'The Row', description: 'American luxury fashion brand' },
  { name: 'By Far', description: 'Bulgarian luxury accessories brand' },
  { name: 'Malone Souliers', description: 'British luxury footwear brand' },
  { name: 'Salvatore Ferragamo', description: 'Italian luxury fashion house' },
  { name: 'Missoni', description: 'Italian luxury fashion house' },
  { name: 'Brunello Cucinelli', description: 'Italian luxury fashion brand' },
  { name: 'Loro Piana', description: 'Italian luxury fashion brand' },
  { name: 'Goyard', description: 'French luxury trunk and leather goods maker' },
  { name: 'Longchamp', description: 'French luxury leather goods company' },
  { name: 'Judith Leiber', description: 'American luxury handbag brand' },
  { name: 'Herschel', description: 'Canadian bag and accessories brand' },
  { name: 'Rimowa', description: 'German luxury luggage brand' },
  { name: 'Tumi', description: 'American luxury luggage brand' },
  { name: 'Mulberry', description: 'British luxury fashion company' },
  { name: 'Dents', description: 'British glove manufacturer' },
  { name: 'Maison Michel', description: 'French millinery house' },
  { name: 'Lack of Color', description: 'Australian hat brand' },
  { name: 'New Era', description: 'American headwear company' },
  { name: 'Alexandre de Paris', description: 'French hair accessories brand' },
  { name: 'Jennifer Behr', description: 'American hair accessories brand' },
  { name: 'Brioni', description: 'Italian luxury menswear brand' },
  { name: 'Turnbull & Asser', description: 'British luxury shirtmaker' },
  { name: 'Charvet', description: 'French luxury shirtmaker' },
  { name: 'Dunhill', description: 'British luxury goods brand' },
  { name: 'Montblanc', description: 'German luxury goods company' },

  // Jewelry & Watches
  { name: 'Cartier', description: 'French luxury jewelry and watch brand' },
  { name: 'Tiffany & Co.', description: 'American luxury jewelry brand' },
  { name: 'Van Cleef & Arpels', description: 'French luxury jewelry brand' },
  { name: 'Bulgari', description: 'Italian luxury jewelry brand' },
  { name: 'Harry Winston', description: 'American luxury jeweler' },
  { name: 'Pomellato', description: 'Italian luxury jewelry brand' },
  { name: 'David Yurman', description: 'American luxury jewelry brand' },
  { name: 'Chopard', description: 'Swiss luxury watch and jewelry brand' },
  { name: 'Piaget', description: 'Swiss luxury watch and jewelry brand' },
  { name: 'Boucheron', description: 'French luxury jewelry brand' },
  { name: 'Graff', description: 'British luxury jewelry brand' },
  { name: 'Mikimoto', description: 'Japanese luxury pearl jewelry brand' },
  { name: 'Swarovski', description: 'Austrian crystal and jewelry brand' },
  { name: 'Pandora', description: 'Danish jewelry brand' },

  // Luxury Watches
  { name: 'Rolex', description: 'Swiss luxury watch brand' },
  { name: 'Patek Philippe', description: 'Swiss luxury watch brand' },
  { name: 'Audemars Piguet', description: 'Swiss luxury watch brand' },
  { name: 'Omega', description: 'Swiss luxury watch brand' },
  { name: 'IWC', description: 'Swiss luxury watch brand' },
  { name: 'TAG Heuer', description: 'Swiss luxury watch brand' },
  { name: 'Breitling', description: 'Swiss luxury watch brand' },
  { name: 'Tudor', description: 'Swiss watch brand' },
  { name: 'Longines', description: 'Swiss watch brand' },
  { name: 'Jaeger-LeCoultre', description: 'Swiss luxury watch brand' },
  { name: 'Vacheron Constantin', description: 'Swiss luxury watch brand' },
  { name: 'A. Lange & Söhne', description: 'German luxury watch brand' },
  { name: 'Panerai', description: 'Italian luxury watch brand' },
  { name: 'Hublot', description: 'Swiss luxury watch brand' },
  { name: 'Zenith', description: 'Swiss luxury watch brand' },
  { name: 'Girard-Perregaux', description: 'Swiss luxury watch brand' },
  { name: 'Blancpain', description: 'Swiss luxury watch brand' },
  { name: 'Ulysse Nardin', description: 'Swiss luxury watch brand' },
  { name: 'Bell & Ross', description: 'French-Swiss watch brand' },
  { name: 'Oris', description: 'Swiss watch brand' },
  { name: 'Tissot', description: 'Swiss watch brand' },
  { name: 'Hamilton', description: 'Swiss-American watch brand' },
  { name: 'Seiko', description: 'Japanese watch brand' },
  { name: 'Grand Seiko', description: 'Japanese luxury watch brand' },
  { name: 'Citizen', description: 'Japanese watch brand' },
  { name: 'Casio', description: 'Japanese electronics and watch brand' },
  { name: 'G-Shock', description: 'Japanese shock-resistant watch brand by Casio' },
  { name: 'Fossil', description: 'American watch and accessories brand' },
  { name: 'Movado', description: 'Swiss-American watch brand' },
  { name: 'Raymond Weil', description: 'Swiss watch brand' },
  { name: 'Frederique Constant', description: 'Swiss watch brand' },
  { name: 'Maurice Lacroix', description: 'Swiss watch brand' },
  { name: 'Baume & Mercier', description: 'Swiss watch brand' },
  { name: 'Richard Mille', description: 'Swiss luxury watch brand' },
  { name: 'Roger Dubuis', description: 'Swiss luxury watch brand' },
  { name: 'Franck Muller', description: 'Swiss luxury watch brand' },
  { name: 'Jacob & Co.', description: 'American luxury watch and jewelry brand' },
  { name: 'Daniel Wellington', description: 'Swedish watch brand' },
  { name: 'MVMT', description: 'American watch and accessories brand' },
  { name: 'Timex', description: 'American watch brand' },
  { name: 'Swatch', description: 'Swiss watch brand' },
  { name: 'Apple Watch', description: 'American smartwatch by Apple' },
  { name: 'Samsung Galaxy Watch', description: 'South Korean smartwatch by Samsung' },
  { name: 'Garmin', description: 'American GPS and smartwatch brand' },
  { name: 'Fitbit', description: 'American fitness tracker and smartwatch brand' },

  // Fast Fashion & Retail
  { name: 'Zara', description: 'Spanish fast fashion retailer' },
  { name: 'H&M', description: 'Swedish multinational clothing company' },
  { name: 'Uniqlo', description: 'Japanese casual wear designer and retailer' },
  { name: 'Gap', description: 'American clothing and accessories retailer' },
  { name: "Levi's", description: 'American clothing company known for denim jeans' },
  { name: 'Forever 21', description: 'American fast fashion retailer' },
  { name: 'Primark', description: 'Irish fast fashion retailer' },
  { name: 'ASOS', description: 'British online fashion retailer' },
  { name: 'Shein', description: 'Chinese online fast fashion retailer' },
  { name: 'Boohoo', description: 'British online fashion retailer' },
  { name: 'Mango', description: 'Spanish clothing design and manufacturing company' },
  { name: 'Massimo Dutti', description: 'Spanish clothing manufacturer' },
  { name: 'Pull & Bear', description: 'Spanish clothing and accessories retailer' },
  { name: 'Bershka', description: 'Spanish clothing retailer' },
  { name: 'Stradivarius', description: 'Spanish fashion brand' },

  // Premium & Designer
  { name: 'Calvin Klein', description: 'American fashion house' },
  { name: 'Tommy Hilfiger', description: 'American premium clothing brand' },
  { name: 'Ralph Lauren', description: 'American fashion company' },
  { name: 'Hugo Boss', description: 'German luxury fashion house' },
  { name: 'Armani', description: 'Italian luxury fashion house' },
  { name: 'Dolce & Gabbana', description: 'Italian luxury fashion house' },
  { name: 'Michael Kors', description: 'American luxury fashion company' },
  { name: 'Coach', description: 'American luxury fashion company' },
  { name: 'Kate Spade', description: 'American luxury fashion design house' },
  { name: 'Tory Burch', description: 'American fashion label' },
  { name: 'Marc Jacobs', description: 'American fashion designer brand' },
  { name: 'Diane von Furstenberg', description: 'American fashion brand' },
  { name: 'Oscar de la Renta', description: 'Dominican-American fashion house' },
  { name: 'Carolina Herrera', description: 'Venezuelan fashion brand' },
  { name: 'Elie Saab', description: 'Lebanese fashion designer brand' },
  { name: 'Balmain', description: 'French luxury fashion house' },
  { name: 'Kenzo', description: 'French luxury fashion house' },
  { name: 'Moschino', description: 'Italian luxury fashion house' },
  { name: 'Vivienne Westwood', description: 'British fashion brand' },
  { name: 'Paul Smith', description: 'British fashion brand' },
  { name: 'Ted Baker', description: 'British luxury clothing brand' },
  { name: 'AllSaints', description: 'British fashion retailer' },
  { name: 'Reiss', description: 'British fashion brand' },
  { name: 'Sandro', description: 'French fashion brand' },
  { name: 'Maje', description: 'French fashion brand' },
  { name: 'Zadig & Voltaire', description: 'French fashion brand' },
  { name: 'Isabel Marant', description: 'French fashion designer brand' },
  { name: 'Equipment', description: 'American fashion brand' },
  { name: 'Jacquemus', description: 'French fashion brand' },

  // Sportswear & Athletic
  { name: 'Puma', description: 'German multinational sportswear company' },
  { name: 'Reebok', description: 'American fitness footwear and apparel company' },
  { name: 'New Balance', description: 'American sports footwear and apparel brand' },
  { name: 'Converse', description: 'American shoe company' },
  { name: 'Vans', description: 'American manufacturer of skateboarding shoes' },
  { name: 'Under Armour', description: 'American sports equipment company' },
  { name: 'ASICS', description: 'Japanese athletic equipment company' },
  { name: 'Fila', description: 'Italian-Korean sportswear company' },
  { name: 'Champion', description: 'American sportswear brand' },
  { name: 'Skechers', description: 'American footwear company' },
  { name: 'Jordan', description: 'American athletic footwear brand by Nike' },
  { name: 'Lululemon', description: 'Canadian athletic apparel retailer' },
  { name: 'Gymshark', description: 'British fitness apparel brand' },
  { name: 'Alo Yoga', description: 'American yoga-inspired clothing brand' },
  { name: 'Athleta', description: 'American athletic apparel brand' },
  { name: 'Outdoor Voices', description: 'American activewear brand' },
  { name: 'Speedo', description: 'Australian swimwear brand' },

  // Outdoor & Lifestyle
  { name: 'The North Face', description: 'American outdoor recreation products company' },
  { name: 'Patagonia', description: 'American outdoor clothing company' },
  { name: 'Columbia', description: 'American outdoor apparel company' },
  { name: 'Moncler', description: 'Italian luxury fashion brand' },
  { name: 'Canada Goose', description: 'Canadian outdoor clothing company' },
  { name: 'Stone Island', description: 'Italian luxury menswear brand' },
  { name: "Arc'teryx", description: 'Canadian outdoor clothing company' },
  { name: 'Fjällräven', description: 'Swedish outdoor equipment company' },
  { name: 'Helly Hansen', description: 'Norwegian outdoor clothing brand' },
  { name: 'Timberland', description: 'American outdoor footwear and apparel brand' },
  { name: 'Carhartt', description: 'American apparel company known for workwear' },
  { name: 'Dickies', description: 'American workwear brand' },

  // Contemporary & Streetwear
  { name: 'Acne Studios', description: 'Swedish luxury fashion house' },
  { name: 'A.P.C.', description: 'French ready-to-wear brand' },
  { name: 'COS', description: 'European fashion brand offering modern wardrobe essentials' },
  { name: 'Supreme', description: 'American skateboarding and streetwear brand' },
  { name: 'Stüssy', description: 'American streetwear brand' },
  { name: 'A Bathing Ape', description: 'Japanese streetwear brand' },
  { name: 'Palace', description: 'British skateboarding and streetwear brand' },
  { name: 'Fear of God', description: 'American luxury streetwear brand' },
  { name: 'Vetements', description: 'Swiss fashion brand' },
  { name: 'Comme des Garçons', description: 'Japanese fashion label' },
  { name: 'Yohji Yamamoto', description: 'Japanese fashion designer brand' },
  { name: 'Issey Miyake', description: 'Japanese fashion designer brand' },
  { name: 'Maison Margiela', description: 'French fashion house' },
  { name: 'Rick Owens', description: 'American fashion designer brand' },
  { name: 'Thom Browne', description: 'American fashion designer brand' },
  { name: 'Rag & Bone', description: 'American fashion brand' },
  { name: 'Theory', description: 'American fashion brand' },
  { name: 'Vince', description: 'American fashion brand' },
  { name: 'Club Monaco', description: 'Canadian fashion brand' },
  { name: 'J.Crew', description: 'American clothing retailer' },
  { name: 'Banana Republic', description: 'American clothing and accessories retailer' },
  { name: 'Everlane', description: 'American clothing retailer focused on ethical fashion' },
  { name: 'Reformation', description: 'American sustainable fashion brand' },

  // Footwear Specialists
  { name: 'Jimmy Choo', description: 'British luxury fashion house specializing in shoes' },
  { name: 'Manolo Blahnik', description: 'Spanish footwear brand' },
  { name: 'Christian Louboutin', description: 'French luxury footwear brand' },
  { name: 'Stuart Weitzman', description: 'American footwear designer brand' },
  { name: 'Steve Madden', description: 'American footwear company' },
  { name: 'Sam Edelman', description: 'American footwear brand' },
  { name: 'Dr. Martens', description: 'British footwear and clothing brand' },
  { name: 'Clarks', description: 'British shoe manufacturer' },
  { name: 'Birkenstock', description: 'German footwear brand' },
  { name: 'UGG', description: 'American footwear company' },
  { name: 'Crocs', description: 'American footwear company' },
  { name: 'TOMS', description: 'American footwear and accessories company' },
  { name: "Tod's", description: 'Italian luxury footwear brand' },
  { name: "Church's", description: 'British luxury footwear brand' },
  { name: 'G.H. Bass', description: 'American footwear brand' },
  { name: 'Repetto', description: 'French footwear and dance brand' },
  { name: "Rothy's", description: 'American sustainable footwear brand' },
  { name: 'Castañer', description: 'Spanish espadrille brand' },
  { name: 'Soludos', description: 'American espadrille brand' },
  { name: 'Ancient Greek Sandals', description: 'Greek sandal brand' },

  // Denim & Casual
  { name: 'Wrangler', description: 'American jeans brand' },
  { name: 'Lee', description: 'American denim brand' },
  { name: 'Diesel', description: 'Italian denim and casual wear brand' },
  { name: 'G-Star Raw', description: 'Dutch denim brand' },
  { name: 'True Religion', description: 'American denim brand' },
  { name: '7 For All Mankind', description: 'American denim brand' },
  { name: 'Citizens of Humanity', description: 'American denim brand' },
  { name: 'AG Jeans', description: 'American premium denim brand' },
  { name: 'Frame', description: 'American denim brand' },
  { name: 'Mother Denim', description: 'American denim brand' },

  // Eyewear
  { name: 'Ray-Ban', description: 'American-Italian eyewear brand' },
  { name: 'Oakley', description: 'American sports eyewear brand' },

  // Lingerie & Swimwear
  { name: 'Agent Provocateur', description: 'British lingerie brand' },
  { name: 'La Perla', description: 'Italian luxury lingerie brand' },
  { name: "Victoria's Secret", description: 'American lingerie brand' },
  { name: 'Fleur du Mal', description: 'American luxury lingerie brand' },
  { name: 'Chantelle', description: 'French lingerie brand' },
  { name: 'Eres', description: 'French luxury swimwear brand' },
  { name: 'Zimmermann', description: 'Australian fashion brand' },
  { name: 'Solid & Striped', description: 'American swimwear brand' },
  { name: 'Vilebrequin', description: 'French swimwear brand' },
  { name: 'Orlebar Brown', description: 'British swimwear brand' },

  // Accessories
  { name: "Drake's", description: 'British accessories brand' },
  { name: 'Aquascutum', description: 'British luxury fashion brand' },

  // African & Ghanaian Brands
  { name: 'Christie Brown', description: 'Ghanaian luxury fashion brand by Aisha Ayensu' },
  { name: 'Duaba Serwa', description: 'Ghanaian fashion brand known for contemporary African designs' },
  { name: 'Pistis Ghana', description: 'Ghanaian fashion house specializing in bridal and evening wear' },
  { name: 'Kiki Clothing', description: 'Ghanaian fashion brand blending African and Western styles' },
  { name: 'Vlisco', description: 'Dutch-African wax print textile company' },
  { name: 'Woodin', description: 'African fashion brand specializing in wax prints' },
  { name: 'GTP', description: 'Ghana Textiles Printing - Ghanaian wax print manufacturer' },
  { name: 'ATL', description: 'Akosombo Textiles Limited - Ghanaian textile manufacturer' },
  { name: 'Batakari', description: 'Traditional Ghanaian smock and northern attire brand' },
  { name: 'Afro Mod Trends', description: 'Ghanaian fashion brand by Ohemaa Poku' },
  { name: 'Steve French', description: 'Ghanaian menswear designer' },
  { name: 'Tongoro', description: 'Senegalese fashion brand by Sarah Diouf' },
  { name: 'AAKS', description: 'Ghanaian handcrafted raffia bag brand' },
  { name: 'Osei-Duro', description: 'Ghanaian-American fashion brand using traditional techniques' },
  { name: 'Studio 189', description: 'African fashion brand by Rosario Dawson and Abrima Erwiah' },
  { name: 'Orange Culture', description: 'Nigerian contemporary menswear brand' },
  { name: 'Lisa Folawiyo', description: 'Nigerian fashion brand known for Ankara luxury fashion' },
  { name: 'Maki Oh', description: 'Nigerian fashion brand by Amaka Osakwe' },
  { name: 'Kenneth Ize', description: 'Nigerian fashion designer known for aso-oke fabrics' },
  { name: 'Thebe Magugu', description: 'South African fashion designer, LVMH Prize winner' },
  { name: 'Rich Mnisi', description: 'South African fashion brand' },
  { name: 'MaXhosa by Laduma', description: 'South African knitwear brand inspired by Xhosa culture' },
  { name: 'EDUN', description: 'African fashion brand promoting trade in Africa' },
  { name: 'Sindiso Khumalo', description: 'South African sustainable fashion designer' },
  { name: 'LaFalaise Dion', description: 'Ivorian haute couture fashion house' },
  { name: 'Imane Ayissi', description: 'Cameroonian haute couture designer' },
  { name: 'Maison ARTC', description: 'Moroccan luxury fashion house' },
  { name: 'Tribal Marks', description: 'Ghanaian fashion brand celebrating African heritage' },
  { name: 'Bestow Elan', description: 'Ghanaian bespoke menswear brand' },
  { name: 'Casa Afia', description: 'Ghanaian fashion brand for contemporary African wear' },
]

export const seedBrands = async (payload: Payload): Promise<void> => {
  payload.logger.info('Seeding brands...')

  let created = 0
  let skipped = 0

  for (const brand of fashionBrands) {
    const slug = brand.name
      .toLowerCase()
      .trim()
      .replace(/\s+/g, '-')
      .replace(/[^a-z0-9-]/g, '')

    // Check if brand already exists by slug
    const existing = await payload.find({
      collection: 'brands',
      where: {
        slug: { equals: slug },
      },
      limit: 1,
    })

    if (existing.docs.length > 0) {
      skipped++
      continue
    }

    await payload.create({
      collection: 'brands',
      data: {
        name: brand.name,
        slug,
      },
    })
    created++
    payload.logger.info(`Created brand: ${brand.name}`)
  }

  payload.logger.info(`Brands seeding complete! Created: ${created}, Skipped (already exist): ${skipped}`)
}
