import type { TaskConfig } from 'payload'
import { ObjectId } from 'mongodb'

/**
 * Process Single Seller Transfer Task
 *
 * Processes a transfer for a single seller. This task is queued by the
 * autoTransferToSellers scheduler task for each seller with a positive balance.
 *
 * The balance is calculated from:
 * - order_payment transactions (positive, older than cutoff)
 * - transfer transactions (negative)
 *
 * Once a transfer is created, the balance goes to zero, so no duplicates.
 */
export const processSellerTransferTask: TaskConfig = {
  slug: 'processSellerTransfer' as any,
  retries: 2,
  inputSchema: [{ name: 'sellerId', type: 'text', required: true }],
  outputSchema: [
    { name: 'transferred', type: 'number' },
    { name: 'success', type: 'checkbox' },
  ],
  handler: async ({ input, req }) => {
    const { payload } = req
    const { sellerId } = input as { sellerId: string }

    try {
      // Calculate cutoff time (5 minutes ago) - for testing
      const cutoffTime = new Date()
      cutoffTime.setMinutes(cutoffTime.getMinutes() - 5)

      // Use MongoDB aggregation to calculate this seller's balance
      const db = payload.db
      const transactionsCollection = db.collections['transactions']

      // Convert sellerId to ObjectId for MongoDB query
      const sellerObjectId = new ObjectId(sellerId)
      payload.logger.info(`[ProcessSellerTransfer] Processing seller ${sellerId} - ${sellerObjectId}`)

      // Calculate balance: order_payments (older than cutoff) + transfers (completed or pending)
      // Only return if balance > 0 (filter in aggregation for atomicity)
      const pipeline = [
        {
          $match: {
            user: sellerObjectId,
            $or: [
              // Completed order_payments older than cutoff
              { type: 'order_payment', status: 'completed', createdAt: { $lt: cutoffTime } },
              // Transfers (completed or pending) - include pending to avoid duplicate transfers
              { type: 'transfer', status: { $in: ['completed', 'pending'] } },
            ],
          },
        },
        {
          $group: {
            _id: '$user',
            balance: { $sum: '$amount' },
            currency: { $first: '$currency' },
          },
        },
        {
          // Only include if positive balance (prevents race conditions)
          $match: {
            balance: { $gt: 0 },
          },
        },
        {
          $lookup: {
            from: 'currencies',
            localField: 'currency',
            foreignField: '_id',
            as: 'currencyDoc',
          },
        },
        {
          $unwind: {
            path: '$currencyDoc',
            preserveNullAndEmptyArrays: true,
          },
        },
      ]

      const results: Array<{
        _id: any
        balance: number
        currency: any
        currencyDoc?: { symbol?: string }
      }> = await transactionsCollection.aggregate(pipeline)

      // If no results, seller has no positive balance (already transferred or no payments)
      if (results.length === 0) {
        payload.logger.info(`[ProcessSellerTransfer] Seller ${sellerId} has no positive balance - skipping`)
        return {
          output: {
            transferred: 0,
            success: true,
          },
        }
      }

      const { balance, currency, currencyDoc } = results[0]
      const currencyId = currency ? currency.toString() : undefined
      const currencySymbol = currencyDoc?.symbol || '₵'

      // Create transfer transaction (negative amount to zero out the balance)
      await payload.create({
        collection: 'transactions',
        data: {
          transactionId: '', // Auto-generated by hook
          type: 'transfer',
          user: sellerId,
          amount: -balance,
          status: 'completed',
          ...(currencyId && { currency: currencyId }),
          notes: `Auto-transfer (TESTING) - Balance: ${currencySymbol}${balance.toFixed(2)}`,
        },
      })

      // Create notification for seller
      await payload.create({
        collection: 'notifications',
        data: {
          user: sellerId,
          type: 'system',
          message: `An amount of ${currencySymbol}${balance.toFixed(2)} has been transferred to your withdrawal account 💰`,
          path: `/users/${sellerId}/details?tab=transactions`,
          read: false,
        },
      })

      payload.logger.info(
        `[ProcessSellerTransfer] Created transfer of ${currencySymbol}${balance.toFixed(2)} for seller ${sellerId}`,
      )

      return {
        output: {
          transferred: balance,
          success: true,
        },
      }
    } catch (error) {
      payload.logger.error(`[ProcessSellerTransfer] Error for seller ${sellerId}: ${error}`)
      throw error
    }
  },
}
