import { PayloadHandler } from 'payload'
import { initializePayment, toSmallestUnit } from '../../../utilities/paystack'

/**
 * POST /api/carts/place-order
 * Place an order from a cart with shipping address
 * 
 * Body: { cartId: string, shippingAddressId: string }
 */
export const placeOrder: PayloadHandler = async (req) => {
  const { payload, user } = req

  if (!user) {
    return Response.json(
      { error: 'Authentication required' },
      { status: 401 }
    )
  }

  try {
    // Parse request body
    const body = await req.json?.() as { cartId?: string; shippingAddressId?: string } | undefined

    if (!body?.cartId) {
      return Response.json(
        { error: 'Cart ID is required' },
        { status: 400 }
      )
    }

    if (!body?.shippingAddressId) {
      return Response.json(
        { error: 'Shipping address ID is required' },
        { status: 400 }
      )
    }

    // Find the cart and verify ownership
    const cart = await payload.findByID({
      collection: 'carts',
      id: body.cartId,
      depth: 0,
    })

    if (!cart) {
      return Response.json(
        { error: 'Cart not found' },
        { status: 404 }
      )
    }

    // Verify ownership
    const cartCustomerId = typeof cart.customer === 'object' ? cart.customer.id : cart.customer
    if (cartCustomerId !== user.id) {
      return Response.json(
        { error: 'Unauthorized to place order for this cart' },
        { status: 403 }
      )
    }

    // Check cart status
    if (cart.status !== 'active') {
      return Response.json(
        { error: 'Cart is not active' },
        { status: 400 }
      )
    }

    // Check cart has items
    if (!cart.items || (cart.items as unknown[]).length === 0) {
      return Response.json(
        { error: 'Cart is empty' },
        { status: 400 }
      )
    }

    // Get the shipping address from user's addresses array
    const userDoc = await payload.findByID({
      collection: 'users',
      id: user.id,
      depth: 2, // Get populated country, region, city
    })

    if (!userDoc?.addresses) {
      return Response.json(
        { error: 'No addresses found' },
        { status: 400 }
      )
    }

    // Find the shipping address by ID
    const addresses = userDoc.addresses as Array<{
      id?: string
      label?: string
      fullName?: string
      phone?: string
      address?: string
      country?: { id: string; name?: string } | string
      region?: { id: string; name?: string } | string
      city?: { id: string; name?: string } | string
      postalCode?: string
      deliveryNotes?: string
      isDefault?: boolean
    }>

    const shippingAddress = addresses.find(addr => addr.id === body.shippingAddressId)

    if (!shippingAddress) {
      return Response.json(
        { error: 'Shipping address not found' },
        { status: 404 }
      )
    }

    // Convert cart to order by changing status to 'converted'
    // Pass shipping address data in context for the hook to use
    const updatedCart = await payload.update({
      collection: 'carts',
      id: body.cartId,
      data: {
        status: 'converted',
      },
      context: {
        shippingAddress: {
          fullName: shippingAddress.fullName || '',
          phone: shippingAddress.phone || '',
          address: shippingAddress.address || '',
          city: typeof shippingAddress.city === 'object' ? shippingAddress.city.name : '',
          cityId: typeof shippingAddress.city === 'object' ? shippingAddress.city.id : shippingAddress.city,
          region: typeof shippingAddress.region === 'object' ? shippingAddress.region.name : '',
          regionId: typeof shippingAddress.region === 'object' ? shippingAddress.region.id : shippingAddress.region,
          country: typeof shippingAddress.country === 'object' ? shippingAddress.country.name : '',
          countryId: typeof shippingAddress.country === 'object' ? shippingAddress.country.id : shippingAddress.country,
          postalCode: shippingAddress.postalCode || '',
          deliveryNotes: shippingAddress.deliveryNotes || '',
        },
      },
      depth: 0,
    })

    // Find the created order by cart ID
    const orders = await payload.find({
      collection: 'orders',
      where: {
        cart: { equals: body.cartId },
      },
      limit: 1,
      depth: 1,
    })

    const order = orders.docs[0]

    if (!order) {
      return Response.json(
        { error: 'Order was not created' },
        { status: 500 }
      )
    }

    // Create a deposit transaction for this order
    const transaction = await payload.create({
      collection: 'transactions',
      data: {
        transactionId: '', // Auto-generated by hook
        type: 'deposit',
        status: 'pending',
        user: user.id,
        order: order.id,
        amount: order.grandTotal || 0,
        notes: `Payment for order ${order.orderId}`,
      },
      overrideAccess: true,
      draft: false,
    })

    // Link the transaction to the order
    // Use skipCommissionCalculation to avoid triggering commission hook and potential write conflicts
    await payload.update({
      collection: 'orders',
      id: order.id,
      data: {
        paymentTransaction: transaction.id,
      },
      overrideAccess: true,
      draft: false,
      context: {
        skipCommissionCalculation: true,
      },
    })

    // Initialize Paystack payment with transaction ID as reference
    const paymentResult = await initializePayment({
      email: user.email,
      amount: toSmallestUnit(order.grandTotal || 0),
      reference: transaction.transactionId,
      currency: 'GHS',
      metadata: {
        orderId: order.id,
        orderNumber: order.orderId,
        transactionId: transaction.id,
        customerId: user.id,
      },
    })

    if (!paymentResult.success || !paymentResult.data) {
      // Update transaction status to cancelled if payment init failed
      await payload.update({
        collection: 'transactions',
        id: transaction.id,
        data: {
          status: 'cancelled',
          notes: `Payment initialization failed: ${paymentResult.error}`,
        },
      })

      return Response.json(
        { error: 'Failed to initialize payment', message: paymentResult.error },
        { status: 500 }
      )
    }

    // Get currency info
    const currency = typeof order.currency === 'object' ? order.currency : null

    return Response.json({
      success: true,
      message: 'Order created successfully. Proceed to payment.',
      order: {
        id: order.id,
        orderId: order.orderId,
        status: order.status,
        grandTotal: order.grandTotal,
        totalItems: order.totalItems,
        currency: currency ? {
          code: currency.code,
          symbol: currency.symbol,
        } : null,
      },
      payment: {
        transactionId: transaction.transactionId,
        authorizationUrl: paymentResult.data.authorization_url,
        accessCode: paymentResult.data.access_code,
        reference: paymentResult.data.reference,
      },
    })
  } catch (error: unknown) {
    payload.logger.error(`Error placing order: ${error}`)
    return Response.json(
      {
        error: 'Failed to place order',
        message: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    )
  }
}
