/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    postCategories: PostCategory;
    media: Media;
    attributes: Attribute;
    attributeOptions: AttributeOption;
    'product-boosts': ProductBoost;
    'product-variations': ProductVariation;
    brands: Brand;
    carts: Cart;
    categories: Category;
    cities: City;
    collections: Collection;
    countries: Country;
    currencies: Currency;
    departments: Department;
    'discount-codes': DiscountCode;
    favorites: Favorite;
    follows: Follow;
    materials: Material;
    notifications: Notification;
    orders: Order;
    regions: Region;
    'product-stats': ProductStat;
    reviews: Review;
    shippingRates: ShippingRate;
    transactions: Transaction;
    users: User;
    'user-points': UserPoint;
    products: Product;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    attributes: {
      categories: 'categories';
      options: 'attributeOptions';
    };
    categories: {
      productStats: 'product-stats';
    };
    collections: {
      categories: 'categories';
    };
    departments: {
      categories: 'categories';
    };
    orders: {
      transactions: 'transactions';
    };
    regions: {
      cities: 'cities';
    };
    users: {
      shippingRates: 'shippingRates';
      products: 'products';
      purchases: 'orders';
      sales: 'orders';
      favorites: 'favorites';
      following: 'follows';
      followers: 'follows';
      transactions: 'transactions';
    };
    products: {
      variations: 'product-variations';
      boosts: 'product-boosts';
      stats: 'product-stats';
      reviews: 'reviews';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    postCategories: PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    attributes: AttributesSelect<false> | AttributesSelect<true>;
    attributeOptions: AttributeOptionsSelect<false> | AttributeOptionsSelect<true>;
    'product-boosts': ProductBoostsSelect<false> | ProductBoostsSelect<true>;
    'product-variations': ProductVariationsSelect<false> | ProductVariationsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    currencies: CurrenciesSelect<false> | CurrenciesSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    'discount-codes': DiscountCodesSelect<false> | DiscountCodesSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    follows: FollowsSelect<false> | FollowsSelect<true>;
    materials: MaterialsSelect<false> | MaterialsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    'product-stats': ProductStatsSelect<false> | ProductStatsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    shippingRates: ShippingRatesSelect<false> | ShippingRatesSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'user-points': UserPointsSelect<false> | UserPointsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'fr' | 'de' | 'es' | 'it')
    | ('en' | 'fr' | 'de' | 'es' | 'it')[];
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'en' | 'fr' | 'de' | 'es' | 'it';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | PromoBannerBlock
    | FeaturedGridBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | PostCategory)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Whether background has been removed from this image
   */
  backgroundRemoved?: boolean | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "postCategories".
 */
export interface PostCategory {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | PostCategory;
  breadcrumbs?:
    | {
        doc?: (string | null) | PostCategory;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  /**
   * Your shop or business name
   */
  shopName?: string | null;
  photo?: (string | null) | Media;
  /**
   * Your country (determines currency for products and shipping)
   */
  country: string | Country;
  language?: ('en' | 'fr' | 'de' | 'es' | 'it' | 'pt' | 'nl' | 'ja' | 'zh' | 'ko') | null;
  /**
   * Shipping rates set by this seller
   */
  shippingRates?: {
    docs?: (string | ShippingRate)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Products listed by this seller
   */
  products?: {
    docs?: (string | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Orders placed by this user
   */
  purchases?: {
    docs?: (string | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Orders containing items sold by this user
   */
  sales?: {
    docs?: (string | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Products favorited by this user
   */
  favorites?: {
    docs?: (string | Favorite)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Users this person is following
   */
  following?: {
    docs?: (string | Follow)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Users following this person
   */
  followers?: {
    docs?: (string | Follow)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Transaction history for this user
   */
  transactions?: {
    docs?: (string | Transaction)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Bank account details for receiving payments from sold items
   */
  withdrawalAccount?: {
    /**
     * Account holder name
     */
    accountName?: string | null;
    /**
     * Account number
     */
    accountNumber?: string | null;
    /**
     * Bank or payment provider (e.g., MTN Mobile Money)
     */
    bank?: string | null;
  };
  /**
   * Saved addresses for shipping
   */
  addresses?:
    | {
        /**
         * Address label (e.g., Home, Work, etc.)
         */
        label: string;
        /**
         * Recipient full name
         */
        fullName: string;
        /**
         * Contact phone number
         */
        phone: string;
        /**
         * Street address
         */
        address: string;
        country: string | Country;
        /**
         * Select country first
         */
        region?: (string | null) | Region;
        /**
         * Select country first
         */
        city?: (string | null) | City;
        /**
         * ZIP/Postal code
         */
        postalCode?: string | null;
        /**
         * Special delivery instructions
         */
        deliveryNotes?: string | null;
        /**
         * Set as default shipping address
         */
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  role: 'admin' | 'user';
  accountStatus: 'active' | 'banned' | 'deleted';
  /**
   * When enabled, your products will be hidden from buyers
   */
  vacationMode?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Supported countries with their currencies
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: string;
  /**
   * Country name (e.g., "Ghana")
   */
  name: string;
  /**
   * ISO country code (e.g., "GH")
   */
  code: string;
  /**
   * Default currency for this country
   */
  currency: string | Currency;
  /**
   * Whether this country is available for sellers
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Supported currencies
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "currencies".
 */
export interface Currency {
  id: string;
  /**
   * Full currency name (e.g., "US Dollar")
   */
  name: string;
  /**
   * ISO 4217 currency code (e.g., "USD")
   */
  code: string;
  /**
   * Currency symbol (e.g., "$", "€", "₵")
   */
  symbol: string;
  /**
   * Exchange rate to GHS (base currency). E.g., 1 USD = 15 GHS → enter 15. For GHS, enter 1.
   */
  exchangeRateToGHS: number;
  /**
   * Is this the base currency (GHS)? Only one currency should be marked as base.
   */
  isBaseCurrency?: boolean | null;
  /**
   * Whether this currency is available for use
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Shipping rates set by sellers for their products
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shippingRates".
 */
export interface ShippingRate {
  id: string;
  /**
   * The seller who owns this shipping rate
   */
  user: string | User;
  /**
   * Country (auto-set from seller)
   */
  country: string | Country;
  /**
   * Cities this shipping rate applies to
   */
  cities: (string | City)[];
  /**
   * Delivery cost (in country currency)
   */
  deliveryCost: number;
  /**
   * Order amount above which shipping is free (leave empty for no free shipping)
   */
  freeShippingThreshold?: number | null;
  /**
   * Estimated delivery time
   */
  estimatedDays?: {
    /**
     * Minimum days
     */
    min?: number | null;
    /**
     * Maximum days
     */
    max?: number | null;
  };
  /**
   * Whether this shipping rate is currently active
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cities within countries
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: string;
  /**
   * City name (e.g., "Accra")
   */
  name: string;
  /**
   * Country this city belongs to
   */
  country: string | Country;
  /**
   * Region/State this city belongs to (optional)
   */
  region?: (string | null) | Region;
  updatedAt: string;
  createdAt: string;
}
/**
 * Regions/States within countries
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: string;
  /**
   * Region name (e.g., "Greater Accra")
   */
  name: string;
  /**
   * Country this region belongs to
   */
  country: string | Country;
  /**
   * Cities in this region
   */
  cities?: {
    docs?: (string | City)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Whether this product is a resell from a returned item (e.g., from a thrift store)
   */
  isResell?: boolean | null;
  /**
   * Product images (first image is the main image)
   */
  images: (string | Media)[];
  /**
   * Select a department first to filter available categories
   */
  department: string | Department;
  /**
   * Select a department first to filter available categories
   */
  category?: (string | null) | Category;
  /**
   * Select a category first to filter available brands
   */
  brand?: (string | null) | Brand;
  /**
   * The user selling this product
   */
  seller: string | User;
  /**
   * Current price for this product
   */
  price: number;
  /**
   * Original price before discount (shows as crossed out, e.g., "Was $500")
   */
  compareAtPrice?: number | null;
  /**
   * Final selling price (auto-calculated: price + 10% platform fee)
   */
  sellingPrice?: number | null;
  /**
   * Available quantity (0 = sold out). Leave empty for unlimited stock.
   */
  stock?: number | null;
  /**
   * Select attributes that apply to this product (all optional)
   */
  attributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Product variations with different options, prices, and inventory
   */
  variations?: {
    docs?: (string | ProductVariation)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Boost history for this product
   */
  boosts?: {
    docs?: (string | ProductBoost)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Sales statistics for this product
   */
  stats?: {
    docs?: (string | ProductStat)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Customer reviews for this product
   */
  reviews?: {
    docs?: (string | Review)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: string;
  name: string;
  /**
   * Categories in this department
   */
  categories?: {
    docs?: (string | Category)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  category: string;
  /**
   * Select which collections this falls under (e.g., Dresses, Bottoms, Shoes)
   */
  collections?: (string | Collection)[] | null;
  /**
   * Select which departments this category belongs to
   */
  departments?: (string | Department)[] | null;
  /**
   * Select which brands are available in this category
   */
  brands?: (string | Brand)[] | null;
  /**
   * Attributes available for products in this category (e.g., Fit, Material, Style)
   */
  attributes?: (string | Attribute)[] | null;
  /**
   * Attributes used as variation types (e.g., Size, Color) - select from attributes above
   */
  variantAttributes?: (string | Attribute)[] | null;
  /**
   * Product stats for this category (for top products, sellers, brands)
   */
  productStats?: {
    docs?: (string | ProductStat)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: string;
  name: string;
  /**
   * Categories in this collection
   */
  categories?: {
    docs?: (string | Category)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product attributes like Fit, Material, Style, etc.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes".
 */
export interface Attribute {
  id: string;
  /**
   * Attribute name (e.g., "Fit", "Material", "Style")
   */
  name: string;
  /**
   * Categories that use this attribute
   */
  categories?: {
    docs?: (string | Category)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Options available for this attribute
   */
  options?: {
    docs?: (string | AttributeOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Options for product attributes (e.g., "Slim Fit", "Leather")
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributeOptions".
 */
export interface AttributeOption {
  id: string;
  /**
   * Option name (e.g., "Slim Fit", "Leather", "Cotton")
   */
  name: string;
  /**
   * URL-friendly slug (e.g., "slim-fit", "leather", "cotton")
   */
  slug: string;
  /**
   * The attribute this option belongs to
   */
  attribute: string | Attribute;
  /**
   * Categories that can use this option (leave empty for all categories with this attribute)
   */
  categories?: (string | Category)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tracks product performance - use for top products, sellers, brands per category
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-stats".
 */
export interface ProductStat {
  id: string;
  product: string | Product;
  /**
   * Auto-populated from product
   */
  seller?: (string | null) | User;
  /**
   * Auto-populated from product category
   */
  department?: (string | null) | Department;
  /**
   * Auto-populated from product category
   */
  collection?: (string | null) | Collection;
  /**
   * Auto-populated from product
   */
  category?: (string | null) | Category;
  /**
   * Auto-populated from product
   */
  brand?: (string | null) | Brand;
  /**
   * Total revenue from sales of this product
   */
  totalSales: number;
  /**
   * Number of completed orders for this product
   */
  totalOrders: number;
  /**
   * Total quantity of this product sold
   */
  totalItemsSold: number;
  /**
   * When the last sale was made
   */
  lastSaleAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product variations with specific options, pricing, and inventory
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variations".
 */
export interface ProductVariation {
  id: string;
  title?: string | null;
  /**
   * The product this variation belongs to
   */
  product: string | Product;
  /**
   * Select one option per variant type (e.g., Size: M, Color: Red)
   */
  options: (string | AttributeOption)[];
  /**
   * Base price for this variation
   */
  price: number;
  /**
   * Final selling price (auto-calculated: price + platform fee)
   */
  sellingPrice?: number | null;
  /**
   * Original price before discount (shows as crossed out)
   */
  compareAtPrice?: number | null;
  /**
   * Available quantity (0 = sold out, empty = unlimited)
   */
  stock?: number | null;
  /**
   * Select images from the product gallery for this variation
   */
  images?: (string | Media)[] | null;
  /**
   * Whether this variation is available for purchase
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product boost/featuring for increased visibility
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-boosts".
 */
export interface ProductBoost {
  id: string;
  /**
   * The product to boost
   */
  product: string | Product;
  /**
   * Boost tier determines visibility priority and duration
   */
  tier: 'basic' | 'standard' | 'premium';
  /**
   * Auto-calculated based on dates
   */
  status: 'scheduled' | 'active' | 'expired' | 'cancelled';
  /**
   * When the boost starts
   */
  startDate: string;
  /**
   * When the boost ends
   */
  endDate: string;
  /**
   * The payment transaction for this boost (optional)
   */
  transaction?: (string | null) | Transaction;
  /**
   * Additional notes about this boost
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Payment transactions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  /**
   * Unique transaction identifier (auto-generated)
   */
  transactionId: string;
  /**
   * Type of transaction
   */
  type: 'transfer' | 'deposit' | 'refund';
  /**
   * Transaction status
   */
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
  /**
   * The user for this transaction
   */
  user: string | User;
  /**
   * The order this transaction belongs to
   */
  order: string | Order;
  /**
   * The order item ID this transaction is for (used to prevent duplicates)
   */
  itemId?: string | null;
  /**
   * Transaction amount (seller payout)
   */
  amount: number;
  fees?: number | null;
  /**
   * Calculated: 1.95% × selling price
   */
  paystackFees?: number | null;
  /**
   * Calculated: fees - paystackFees
   */
  commissionFees?: number | null;
  /**
   * Payment account information
   */
  billingDetails?: {
    /**
     * Account holder name
     */
    accountName?: string | null;
    /**
     * Account number
     */
    accountNumber?: string | null;
    /**
     * Bank or payment provider (e.g., MTN Mobile Money)
     */
    bank?: string | null;
  };
  /**
   * Additional notes about this transaction
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer orders
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Unique order identifier (auto-generated)
   */
  orderId: string;
  /**
   * Auto-calculated: Placed (all placed), In Progress (items in transit), Completed (all delivered/returned), Cancelled (all returned)
   */
  status: 'placed' | 'in_progress' | 'completed' | 'cancelled';
  /**
   * The customer who placed this order
   */
  customer: string | User;
  /**
   * All sellers involved in this order (auto-populated)
   */
  sellers?: (string | User)[] | null;
  /**
   * Order items with individual shipping status
   */
  items: {
    /**
     * Reference to the product
     */
    product?: (string | null) | Product;
    /**
     * The seller of this item
     */
    seller?: (string | null) | User;
    /**
     * Product title at time of purchase
     */
    productTitle: string;
    /**
     * Seller name at time of purchase
     */
    sellerName?: string | null;
    /**
     * URL to product image at time of purchase
     */
    productImage?: string | null;
    /**
     * Selected variation options (e.g., {"Size": "M", "Color": "Blue"})
     */
    variationOptions?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * ID of the selected variation (for stock management)
     */
    variationId?: string | null;
    /**
     * Selling price (what customer paid)
     */
    price: number;
    /**
     * Original price before commission
     */
    originalPrice?: number | null;
    quantity: number;
    shippingFee?: number | null;
    /**
     * Buyer protection enabled
     */
    buyerProtection?: boolean | null;
    /**
     * 80% of shipping fee if enabled
     */
    buyerProtectionFee?: number | null;
    /**
     * Shipping status for this item
     */
    shippingStatus: 'placed' | 'out_for_delivery' | 'delivered' | 'return_in_progress' | 'returned' | 'not_available';
    /**
     * History of status changes
     */
    statusLogs?:
      | {
          status: string;
          timestamp: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Reason for return (required when returning)
     */
    returnReason?: ('wrong_item' | 'fake_item' | 'damaged' | 'not_as_described') | null;
    /**
     * Photo evidence for return
     */
    returnImage?: (string | null) | Media;
    id?: string | null;
  }[];
  /**
   * Total number of items (auto-calculated)
   */
  totalItems: number;
  /**
   * Subtotal (products only)
   */
  subtotal: number;
  /**
   * Grand total (products + shipping + buyer protection - discount - points)
   */
  grandTotal: number;
  /**
   * Currency (from customer country)
   */
  currency?: (string | null) | Currency;
  /**
   * Applied discount code (reference)
   */
  discountCode?: (string | null) | DiscountCode;
  /**
   * Discount code that was applied (e.g., SAVE20)
   */
  discountCodeUsed?: string | null;
  /**
   * Discount amount applied
   */
  discountAmount?: number | null;
  /**
   * Points redeemed for this order
   */
  pointsRedeemed?: number | null;
  /**
   * Discount from redeemed points
   */
  pointsDiscount?: number | null;
  /**
   * Grand Total - Seller Payout - Paystack Fee - Transfer Fees + Buyer Protection
   */
  totalCommission?: number | null;
  shippingDetails?: {
    /**
     * Recipient full name
     */
    fullName?: string | null;
    /**
     * Contact phone number
     */
    phone?: string | null;
    /**
     * Street address
     */
    address?: string | null;
    city?: string | null;
    /**
     * State/Region/Province
     */
    region?: string | null;
    /**
     * ZIP/Postal code
     */
    postalCode?: string | null;
    country?: string | null;
    /**
     * Special delivery instructions
     */
    deliveryNotes?: string | null;
  };
  billingDetails?: {
    /**
     * Account holder name
     */
    accountName?: string | null;
    /**
     * Account number (e.g., 0243530213)
     */
    accountNumber?: string | null;
    /**
     * Bank or payment provider (e.g., MTN Mobile Money)
     */
    bank?: string | null;
  };
  /**
   * When the order was placed
   */
  placedAt?: string | null;
  /**
   * Internal notes about the order
   */
  notes?: string | null;
  /**
   * Transactions associated with this order
   */
  transactions?: {
    docs?: (string | Transaction)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Discount codes for orders
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes".
 */
export interface DiscountCode {
  id: string;
  /**
   * The discount code (e.g., SAVE10, FREESHIP)
   */
  code: string;
  /**
   * Description of the discount (shown to customers)
   */
  description?: string | null;
  /**
   * Type of discount
   */
  type: 'percentage' | 'fixed' | 'free_shipping';
  /**
   * Discount value (percentage or fixed amount)
   */
  value?: number | null;
  /**
   * Minimum order amount required to use this code
   */
  minOrderAmount?: number | null;
  /**
   * Maximum discount amount (for percentage discounts)
   */
  maxDiscountAmount?: number | null;
  /**
   * Number of times this code has been used
   */
  usageCount?: number | null;
  /**
   * Maximum number of times this code can be used (leave empty for unlimited)
   */
  maxUses?: number | null;
  /**
   * Max uses per user
   */
  maxUsesPerUser?: number | null;
  /**
   * When the code becomes active
   */
  startsAt?: string | null;
  /**
   * When the code expires
   */
  expiresAt?: string | null;
  /**
   * Whether this discount code is active
   */
  active?: boolean | null;
  /**
   * What this discount applies to
   */
  applicableTo?: ('all' | 'categories' | 'products' | 'sellers') | null;
  /**
   * Categories this discount applies to
   */
  categories?: (string | Category)[] | null;
  /**
   * Products this discount applies to
   */
  products?: (string | Product)[] | null;
  /**
   * Sellers whose products this discount applies to
   */
  sellers?: (string | User)[] | null;
  /**
   * Users who have used this code
   */
  usedBy?:
    | {
        user?: (string | null) | User;
        usedAt?: string | null;
        order?: (string | null) | Order;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product reviews from customers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  user: string | User;
  product: string | Product;
  /**
   * Rating from 1 to 5 stars
   */
  rating: number;
  /**
   * Review text
   */
  review?: string | null;
  /**
   * Review images
   */
  images?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User favorite products
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: string;
  /**
   * The user who favorited the product
   */
  user: string | User;
  /**
   * The favorited product
   */
  product: string | Product;
  updatedAt: string;
  createdAt: string;
}
/**
 * User follow relationships
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follows".
 */
export interface Follow {
  id: string;
  /**
   * The user who is following
   */
  follower: string | User;
  /**
   * The user being followed
   */
  following: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBannerBlock".
 */
export interface PromoBannerBlock {
  /**
   * Main headline, e.g. "First Time?"
   */
  title: string;
  /**
   * Supporting text, e.g. "Shop: 10% off with code WELCOMEVC..."
   */
  description: string;
  /**
   * CTA button text
   */
  actionText: string;
  /**
   * Where the CTA button links to
   */
  actionLink: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  backgroundColor?: ('light' | 'white' | 'info' | 'success' | 'warning' | 'error') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'promoBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedGridBlock".
 */
export interface FeaturedGridBlock {
  /**
   * Section title, e.g. "Shop by Category"
   */
  title: string;
  /**
   * Grid items with image and label
   */
  items: {
    image: string | Media;
    /**
     * Text shown below the image, e.g. "CLOTHING"
     */
    label: string;
    /**
     * URL to navigate to when clicked, e.g. "/categories/clothing"
     */
    link?: string | null;
    id?: string | null;
  }[];
  /**
   * Number of columns on desktop
   */
  columns?: ('2' | '3' | '4') | null;
  aspectRatio?: ('square' | 'portrait' | 'landscape') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredGrid';
}
/**
 * Shopping carts for users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  /**
   * The customer who owns this cart
   */
  customer: string | User;
  /**
   * Cart status
   */
  status: 'active' | 'converted' | 'abandoned';
  /**
   * Items in the cart
   */
  items: {
    /**
     * Products available from sellers in your country
     */
    product: string | Product;
    /**
     * Select a variation for this product
     */
    variation?: (string | null) | ProductVariation;
    /**
     * Price (auto-populated from selected variation)
     */
    price?: number | null;
    /**
     * Quantity of this item
     */
    quantity: number;
    /**
     * Shipping fee for this item
     */
    shippingFee?: number | null;
    /**
     * Add buyer protection (80% of shipping fee)
     */
    buyerProtection?: boolean | null;
    /**
     * Buyer protection fee (auto-calculated: 80% of shipping fee)
     */
    buyerProtectionFee?: number | null;
    /**
     * When this item was added to the cart
     */
    addedAt?: string | null;
    id?: string | null;
  }[];
  /**
   * Total number of items in cart (auto-calculated)
   */
  itemCount?: number | null;
  /**
   * Subtotal (products only, before shipping/fees - used for discount calculation)
   */
  subtotal?: number | null;
  /**
   * Grand total (subtotal + shipping + buyer protection - discount)
   */
  grandTotal?: number | null;
  /**
   * Applied discount code (discount applies to subtotal)
   */
  discountCode?: (string | null) | DiscountCode;
  /**
   * Discount amount applied (percentage of subtotal)
   */
  discountAmount?: number | null;
  /**
   * Points to redeem as discount (1 point = 1 currency unit)
   */
  pointsToRedeem?: number | null;
  /**
   * Discount from redeemed points (auto-calculated)
   */
  pointsDiscount?: number | null;
  /**
   * Currency (auto-set from customer country)
   */
  currency?: (string | null) | Currency;
  /**
   * When the cart was converted to an order
   */
  purchasedAt?: string | null;
  /**
   * Optional notes for the order
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials".
 */
export interface Material {
  id: string;
  name: string;
  /**
   * Categories that use this material
   */
  categories?: (string | Category)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User notifications
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  /**
   * The user who receives this notification
   */
  user: string | User;
  /**
   * URL to the notification image/icon
   */
  image?: string | null;
  /**
   * Notification message
   */
  message: string;
  /**
   * Path to navigate to when notification is clicked
   */
  path?: string | null;
  /**
   * Whether the notification has been read
   */
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * User reward points for purchases
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-points".
 */
export interface UserPoint {
  id: string;
  /**
   * The user who owns these points
   */
  user: string | User;
  /**
   * Current available points balance
   */
  balance: number;
  /**
   * Total points earned all-time
   */
  totalEarned: number;
  /**
   * Total points redeemed all-time
   */
  totalRedeemed: number;
  /**
   * Points transaction history
   */
  history?:
    | {
        type: 'earned' | 'redeemed' | 'expired' | 'adjusted';
        /**
         * Points amount (positive for earned, negative for redeemed)
         */
        points: number;
        /**
         * Description of the transaction
         */
        description?: string | null;
        /**
         * Related order (if applicable)
         */
        order?: (string | null) | Order;
        /**
         * When this transaction occurred
         */
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'postCategories';
        value: string | PostCategory;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'attributes';
        value: string | Attribute;
      } | null)
    | ({
        relationTo: 'attributeOptions';
        value: string | AttributeOption;
      } | null)
    | ({
        relationTo: 'product-boosts';
        value: string | ProductBoost;
      } | null)
    | ({
        relationTo: 'product-variations';
        value: string | ProductVariation;
      } | null)
    | ({
        relationTo: 'brands';
        value: string | Brand;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'cities';
        value: string | City;
      } | null)
    | ({
        relationTo: 'collections';
        value: string | Collection;
      } | null)
    | ({
        relationTo: 'countries';
        value: string | Country;
      } | null)
    | ({
        relationTo: 'currencies';
        value: string | Currency;
      } | null)
    | ({
        relationTo: 'departments';
        value: string | Department;
      } | null)
    | ({
        relationTo: 'discount-codes';
        value: string | DiscountCode;
      } | null)
    | ({
        relationTo: 'favorites';
        value: string | Favorite;
      } | null)
    | ({
        relationTo: 'follows';
        value: string | Follow;
      } | null)
    | ({
        relationTo: 'materials';
        value: string | Material;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'regions';
        value: string | Region;
      } | null)
    | ({
        relationTo: 'product-stats';
        value: string | ProductStat;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'shippingRates';
        value: string | ShippingRate;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'user-points';
        value: string | UserPoint;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        promoBanner?: T | PromoBannerBlockSelect<T>;
        featuredGrid?: T | FeaturedGridBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBannerBlock_select".
 */
export interface PromoBannerBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  actionText?: T;
  actionLink?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedGridBlock_select".
 */
export interface FeaturedGridBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        image?: T;
        label?: T;
        link?: T;
        id?: T;
      };
  columns?: T;
  aspectRatio?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "postCategories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  backgroundRemoved?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes_select".
 */
export interface AttributesSelect<T extends boolean = true> {
  name?: T;
  categories?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributeOptions_select".
 */
export interface AttributeOptionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  attribute?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-boosts_select".
 */
export interface ProductBoostsSelect<T extends boolean = true> {
  product?: T;
  tier?: T;
  status?: T;
  startDate?: T;
  endDate?: T;
  transaction?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variations_select".
 */
export interface ProductVariationsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  price?: T;
  sellingPrice?: T;
  compareAtPrice?: T;
  stock?: T;
  images?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  customer?: T;
  status?: T;
  items?:
    | T
    | {
        product?: T;
        variation?: T;
        price?: T;
        quantity?: T;
        shippingFee?: T;
        buyerProtection?: T;
        buyerProtectionFee?: T;
        addedAt?: T;
        id?: T;
      };
  itemCount?: T;
  subtotal?: T;
  grandTotal?: T;
  discountCode?: T;
  discountAmount?: T;
  pointsToRedeem?: T;
  pointsDiscount?: T;
  currency?: T;
  purchasedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  category?: T;
  collections?: T;
  departments?: T;
  brands?: T;
  attributes?: T;
  variantAttributes?: T;
  productStats?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  region?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  name?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  currency?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "currencies_select".
 */
export interface CurrenciesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  symbol?: T;
  exchangeRateToGHS?: T;
  isBaseCurrency?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discount-codes_select".
 */
export interface DiscountCodesSelect<T extends boolean = true> {
  code?: T;
  description?: T;
  type?: T;
  value?: T;
  minOrderAmount?: T;
  maxDiscountAmount?: T;
  usageCount?: T;
  maxUses?: T;
  maxUsesPerUser?: T;
  startsAt?: T;
  expiresAt?: T;
  active?: T;
  applicableTo?: T;
  categories?: T;
  products?: T;
  sellers?: T;
  usedBy?:
    | T
    | {
        user?: T;
        usedAt?: T;
        order?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follows_select".
 */
export interface FollowsSelect<T extends boolean = true> {
  follower?: T;
  following?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials_select".
 */
export interface MaterialsSelect<T extends boolean = true> {
  name?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  image?: T;
  message?: T;
  path?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderId?: T;
  status?: T;
  customer?: T;
  sellers?: T;
  items?:
    | T
    | {
        product?: T;
        seller?: T;
        productTitle?: T;
        sellerName?: T;
        productImage?: T;
        variationOptions?: T;
        variationId?: T;
        price?: T;
        originalPrice?: T;
        quantity?: T;
        shippingFee?: T;
        buyerProtection?: T;
        buyerProtectionFee?: T;
        shippingStatus?: T;
        statusLogs?:
          | T
          | {
              status?: T;
              timestamp?: T;
              id?: T;
            };
        returnReason?: T;
        returnImage?: T;
        id?: T;
      };
  totalItems?: T;
  subtotal?: T;
  grandTotal?: T;
  currency?: T;
  discountCode?: T;
  discountCodeUsed?: T;
  discountAmount?: T;
  pointsRedeemed?: T;
  pointsDiscount?: T;
  totalCommission?: T;
  shippingDetails?:
    | T
    | {
        fullName?: T;
        phone?: T;
        address?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
        deliveryNotes?: T;
      };
  billingDetails?:
    | T
    | {
        accountName?: T;
        accountNumber?: T;
        bank?: T;
      };
  placedAt?: T;
  notes?: T;
  transactions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  cities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-stats_select".
 */
export interface ProductStatsSelect<T extends boolean = true> {
  product?: T;
  seller?: T;
  department?: T;
  collection?: T;
  category?: T;
  brand?: T;
  totalSales?: T;
  totalOrders?: T;
  totalItemsSold?: T;
  lastSaleAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  rating?: T;
  review?: T;
  images?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shippingRates_select".
 */
export interface ShippingRatesSelect<T extends boolean = true> {
  user?: T;
  country?: T;
  cities?: T;
  deliveryCost?: T;
  freeShippingThreshold?: T;
  estimatedDays?:
    | T
    | {
        min?: T;
        max?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  transactionId?: T;
  type?: T;
  status?: T;
  user?: T;
  order?: T;
  itemId?: T;
  amount?: T;
  fees?: T;
  paystackFees?: T;
  commissionFees?: T;
  billingDetails?:
    | T
    | {
        accountName?: T;
        accountNumber?: T;
        bank?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  shopName?: T;
  photo?: T;
  country?: T;
  language?: T;
  shippingRates?: T;
  products?: T;
  purchases?: T;
  sales?: T;
  favorites?: T;
  following?: T;
  followers?: T;
  transactions?: T;
  withdrawalAccount?:
    | T
    | {
        accountName?: T;
        accountNumber?: T;
        bank?: T;
      };
  addresses?:
    | T
    | {
        label?: T;
        fullName?: T;
        phone?: T;
        address?: T;
        country?: T;
        region?: T;
        city?: T;
        postalCode?: T;
        deliveryNotes?: T;
        isDefault?: T;
        id?: T;
      };
  role?: T;
  accountStatus?: T;
  vacationMode?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-points_select".
 */
export interface UserPointsSelect<T extends boolean = true> {
  user?: T;
  balance?: T;
  totalEarned?: T;
  totalRedeemed?: T;
  history?:
    | T
    | {
        type?: T;
        points?: T;
        description?: T;
        order?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  isResell?: T;
  images?: T;
  department?: T;
  category?: T;
  brand?: T;
  seller?: T;
  price?: T;
  compareAtPrice?: T;
  sellingPrice?: T;
  stock?: T;
  attributes?: T;
  variations?: T;
  boosts?: T;
  stats?: T;
  reviews?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}