import type { PayloadHandler } from 'payload'
import { initializePayment, toSmallestUnit } from '../../../utilities/paystack'

/**
 * POST /api/boost-tiers/initiate
 * Initiate a boost payment for a style
 *
 * Body: { styleId: string, tierId: string }
 *
 * Flow:
 * 1. Validate style exists and belongs to user
 * 2. Validate tier exists and is active
 * 3. Create pending transaction with type 'boost_payment'
 * 4. Initialize Paystack payment
 * 5. Return payment URL and transaction ID
 */
export const initiateBoostPayment: PayloadHandler = async (req) => {
  const { payload, user } = req

  if (!user) {
    return Response.json({ error: 'Authentication required' }, { status: 401 })
  }

  try {
    // Parse request body
    const body = (await req.json?.()) as { styleId?: string; tierId?: string } | undefined

    if (!body?.styleId) {
      return Response.json({ error: 'Style ID is required' }, { status: 400 })
    }

    if (!body?.tierId) {
      return Response.json({ error: 'Tier ID is required' }, { status: 400 })
    }

    // Validate style exists and belongs to user
    const style = await payload.findByID({
      collection: 'styles',
      id: body.styleId,
      depth: 0,
    })

    if (!style) {
      return Response.json({ error: 'Style not found' }, { status: 404 })
    }

    // Check ownership
    const styleOwnerId = style.seller 
      ? (typeof style.seller === 'object' ? style.seller.id : style.seller)
      : null
    if (styleOwnerId !== user.id) {
      return Response.json({ error: 'You can only boost your own styles' }, { status: 403 })
    }

    // Check style is published
    if (style.status !== 'published') {
      return Response.json(
        { error: 'Only published styles can be boosted' },
        { status: 400 },
      )
    }

    // Validate tier exists and is active
    const tier = await payload.findByID({
      collection: 'boost-tiers',
      id: body.tierId,
      depth: 0,
    })

    if (!tier) {
      return Response.json({ error: 'Boost tier not found' }, { status: 404 })
    }

    if (!tier.isActive) {
      return Response.json({ error: 'This boost tier is no longer available' }, { status: 400 })
    }

    // Check if style already has an active or scheduled boost (endDate is in the future)
    const now = new Date().toISOString()
    const existingBoosts = await payload.find({
      collection: 'style-boosts',
      where: {
        style: { equals: body.styleId },
        endDate: { greater_than: now }, // Boost hasn't expired yet
      },
      limit: 1,
    })

    if (existingBoosts.docs.length > 0) {
      return Response.json(
        { error: 'This style already has an active or scheduled boost' },
        { status: 400 },
      )
    }

    // Create pending transaction
    // Price is stored in GHS in the database
    const amountInGHS = tier.price as number

    const transaction = await payload.create({
      collection: 'transactions',
      data: {
        transactionId: '', // Auto-generated by hook
        type: 'boost_payment' as const,
        status: 'pending',
        user: user.id,
        style: body.styleId, // Link to the style being boosted
        amount: amountInGHS,
        notes: `Boost payment for style: ${style.title || body.styleId} - ${tier.name} (${tier.duration} days)`,
      },
      overrideAccess: true,
      draft: false,
    })

    // Initialize Paystack payment
    // Paystack requires amount in smallest unit (pesewas)
    const paymentResult = await initializePayment({
      email: user.email,
      amount: toSmallestUnit(amountInGHS),
      reference: transaction.transactionId,
      currency: 'GHS',
      metadata: {
        type: 'boost_payment',
        styleId: body.styleId,
        styleName: style.title || 'Style',
        tierId: body.tierId,
        tierName: tier.name,
        tierDuration: tier.duration,
        transactionId: transaction.id,
        customerId: user.id,
      },
    })

    if (!paymentResult.success || !paymentResult.data) {
      // Update transaction status to cancelled if payment init failed
      await payload.update({
        collection: 'transactions',
        id: transaction.id,
        data: {
          status: 'cancelled',
          notes: `Payment initialization failed: ${paymentResult.error}`,
        },
      })

      return Response.json(
        { error: 'Failed to initialize payment', message: paymentResult.error },
        { status: 500 },
      )
    }

    return Response.json({
      success: true,
      message: 'Payment initialized. Proceed to payment.',
      transaction: {
        id: transaction.id,
        transactionId: transaction.transactionId,
      },
      payment: {
        authorizationUrl: paymentResult.data.authorization_url,
        accessCode: paymentResult.data.access_code,
        reference: paymentResult.data.reference,
      },
      tier: {
        name: tier.name,
        duration: tier.duration,
        price: amountInGHS,
      },
    })
  } catch (error: unknown) {
    payload.logger.error(`Error initiating boost payment: ${error}`)
    return Response.json(
      {
        error: 'Failed to initiate boost payment',
        message: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 },
    )
  }
}
